/**
 * Stable, machine-readable error codes returned in API error responses.
 *
 * These codes are a public contract consumed by web, mobile, and future
 * services. Do not rename existing codes; add new ones instead.
 */
export enum ApiErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REUSED = 'TOKEN_REUSED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  FORBIDDEN = 'FORBIDDEN',
  ORGANIZATION_ACCESS_DENIED = 'ORGANIZATION_ACCESS_DENIED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  DEPENDENCY_UNAVAILABLE = 'DEPENDENCY_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Catalog (Volume 2)
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  DUPLICATE_SKU = 'DUPLICATE_SKU',
  DUPLICATE_VARIANT = 'DUPLICATE_VARIANT',
  INVALID_CATEGORY = 'INVALID_CATEGORY',
  INVALID_PROMOTION = 'INVALID_PROMOTION',
  MEDIA_UPLOAD_CONFLICT = 'MEDIA_UPLOAD_CONFLICT',
  EXTERNAL_STORAGE_FAILURE = 'EXTERNAL_STORAGE_FAILURE',

  // Inventory / cart / checkout (Volume 3)
  INSUFFICIENT_INVENTORY = 'INSUFFICIENT_INVENTORY',
  RESERVATION_CONFLICT = 'RESERVATION_CONFLICT',
  ITEM_UNAVAILABLE = 'ITEM_UNAVAILABLE',
  STALE_PRICE = 'STALE_PRICE',
  CHECKOUT_EXPIRED = 'CHECKOUT_EXPIRED',
  CHECKOUT_ALREADY_COMPLETED = 'CHECKOUT_ALREADY_COMPLETED',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  CART_REVISION_CONFLICT = 'CART_REVISION_CONFLICT',
}
